[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
board_build.filesystem = littlefs
extra_scripts = pre:scripts/generate_wifi_web_assets.py

monitor_speed = 115200
monitor_filters = time

lib_deps =
    zinggjm/GxEPD2
    adafruit/Adafruit GFX Library
